services:
  # API Gateway
  api-gateway:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - type: bind
        source: ./api-gateway/nginx.conf
        target: /etc/nginx/nginx.conf
      - type: bind
        source: ./api-gateway/default.conf
        target: /etc/nginx/conf.d/default.conf
    depends_on:
      - auth-service
      - session-service
      - user-service
      # - payment-service
      # - order-service
      # - menu-service
      # - cart-service
      # - delivery-service
      # - notification-service
    restart: unless-stopped
    networks:
      - nomnom-network

  # Auth Service
  auth-service:
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    env_file:
      - ./auth-service/.env
    restart: unless-stopped
    networks:
      - nomnom-network

  # Session Service
  session-service:
    build:
      context: ./session-service
      dockerfile: Dockerfile
    ports:
      - "5007:5007"
    env_file:
      - ./session-service/.env
    restart: unless-stopped
    networks:
      - nomnom-network

  # User Service
  user-service:
    build:
      context: ./user-service
      dockerfile: Dockerfile
    ports:
      - "8085:8085"
    env_file:
      - ./user-service/.env
    restart: unless-stopped
    networks:
      - nomnom-network


  # Cart Service

networks:
  nomnom-network:
    driver: bridge